Add get_mount_search & get_mount_search_from
stemjail/mnt-rs pull request #1
Opened 2017-10-25 18:17 UTC by tasleson

The existing get_mount only allows you to locate a mount point
by using the file system mounted point.  Sometimes it's useful
to locate the mount points that may be available for a specified
device node.  With this in mind I added a search enum which allows
the caller to match 1 or more mount points by allowing them to
search by any one of the fields in the mount.

**Note:** I believe that the `get_mount_from` comparison should be more specific than

```rust
        match mount {
            Ok(m) => if target.as_ref().starts_with(&m.file) {
                // Get the last entry
                ret = Some(m);
            },
            Err(e) => return Err(e),
        }
```
As it matches far too easily which results in unexpected returned mounts.

2017-10-26 00:17 UTC, agrover commented
Suggest adding docstrings for both of the new methods. 👍

2017-10-26 07:45 UTC, l0kod commented
Thanks for the pull request!

Please add some tests for `get_mount_search_from()`.

You can replace `Result<Option<Vec<...` with `Result<Vec<...` in the return type. No need for an option if there is a vector, on which you will probably iterate through. Thinking more about it, you should return an iterator instead of a vector, this should reduce/remove the main loop. A generator would be perfect but there are not stable yet.

2017-10-26 13:43 UTC, mulkieran commented on src/parse.rs
> +                        // I'm pretty sure there is a more elegant way to do this
Unless there is a compelling reason to avoid using HashSet I'ld do subset inclusion...which as far as I can tell is all this is.

2017-10-26 14:01 UTC, mulkieran requested changes

2017-10-26 14:01 UTC, mulkieran commented on src/parse.rs
> +        -> Result<Option<Vec<MountEntry>>, ParseError> where U: BufRead {
I concur with the suggestion to return an iterator of results.

2017-10-26 14:01 UTC, mulkieran commented on src/parse.rs
> +                match search {
This seems wordy. Why not match on the search and then something like:

```iter().filter(<function that keeps error and all matches>)```

something like:

```|r| r.is_err() || r.spec == spec```

and so forth.

Or something, depending on your attitude to errors.

2017-10-26 19:38 UTC, tasleson commented
@l0kod @mulkieran I tried and failed to convert this to some type of iterator.  I've actually tried a number of different approaches, here are two of them that fail to compile the same way

Creating a new return struct with an iterator [try 1](https://github.com/tasleson/mnt-rs/tree/create_new_iterator)
```
error[E0308]: mismatched types
   --> src/parse.rs:186:48
    |
186 |         Ok(m) => get_mount_search_from(search, m),
    |                                                ^ expected type parameter, found struct `std::io::BufReader`
    |
    = note: expected type `parse::MountIter<U>`
               found type `parse::MountIter<std::io::BufReader<std::fs::File>>`

error: aborting due to previous error
```

Leveraging the existing iterator [try 2](https://github.com/tasleson/mnt-rs/tree/use_existing_itr)
```
error[E0308]: mismatched types
   --> src/parse.rs:179:5
    |
179 |     MountIter::new_from_proc_search(search)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter, found struct `std::io::BufReader`
    |
    = note: expected type `std::result::Result<parse::MountIter<T>, _>`
               found type `std::result::Result<parse::MountIter<std::io::BufReader<std::fs::File>>, _>`

error: aborting due to previous error
```
I still have a ways to go to master the rust language.

2017-10-28 15:57 UTC, tasleson commented
@l0kod @mulkieran OK, I got both sample branches to compile and work, please take a look at each and if either looks like a good path to follow I will clean them up with suggestions given above, thanks!

2017-11-01 20:29 UTC, tasleson commented
@l0kod @mulkieran New updated commit which has:

* New methods now return iterators
* Source docs added
* Unit tests added
* Utilizing `HashSet` when comparing mount option match

2017-11-04 17:19 UTC, l0kod commented
I reworked your commit here: https://github.com/stemjail/mnt-rs/commits/feature-search-pr1

I replaced the `get_mount_search*()` functions with a new method `MountEntry::contains()` and replaced `enum Search` with `enum MountParam`. It is more flexible and lighter this way. ;)

Does it fits your needs?

2017-11-06 18:22 UTC, tasleson commented
@l0kod Yes this will work, thank you!

2017-11-06 23:18 UTC, closed without merging

2017-11-06 23:20 UTC, l0kod commented
You can use mnt-0.3.1 from crates.io